config/routes.rb
Lcbo::Application.routes.draw do
  
  resources :stores
  resources :products

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'open-uri'
  
  def format_price(price_in_cents)
    price_in_dollars = price_in_cents.to_f / 100
  end

  def index
    page = 1
    if params[:page]
      page = params[:page]
    end

    products_json = open("http://lcboapi.com/products?page=#{page}").read
    @products = JSON.parse(products_json)
  end

  def show
    product_json = open("http://lcboapi.com/products/#{params[:id]}").read
    product_hash = JSON.parse(product_json)
    @product = product_hash["result"]
  end

  helper_method :format_price  #allows format_price method to be used in views.
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  require 'open-uri'
  
  def convert_min_to_time(sunday_open)
    time = (sunday_open / 60)
  end
  
  def index
    stores_json = open('http://lcboapi.com/stores?page=10').read
    @stores = JSON.parse(stores_json)
  end

  def show
    store_json = open("http://lcboapi.com/stores/#{params[:id]}").read
    store_hash = JSON.parse(store_json)
    @store = store_hash["result"]
  end

  helper_method :convert_min_to_time
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lcbo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>List of Products</h1>
<%= link_to "<Previous Page", "#{@products['pager']['previous_page_path']}" %>  |  <%= link_to "Next Page >", "#{@products['pager']['next_page_path']}" %>
<br><br>

<% @products['result'].each do |product| %>
  <section>
    <%= link_to product['name'], product_path(product['id']) %>
    <%= format_price product['price_in_cents'] %>
    <%= product['primary_category'] %>
  </section>
<% end %>

app/views/products/show.html.erb
<h1><%= @product["name"] %></h1>
<% if @product["image_thumb_url"]  %>
  <%= image_tag @product["image_thumb_url"] %>
<% else %>
  <%= image_tag("http://2.bp.blogspot.com/_Ze5Xm5fW-4o/TUnUBt6ADUI/AAAAAAAABJA/2WGSLTNK1K4/s1600/broken-link-image-gif.jpg") %>
  <% end %><br>
<ul>
  <li><em>Price: </em>$<%= @product["price_in_cents"].to_f / 100 %></li>
  <li><em>Price per oz: </em>$<%= (@product["price_in_cents"].to_f / 100) / (@product["package_unit_volume_in_milliliters"]*0.033814) %></li>
  <li><em>Inventroy Count in All Stores: </em><%= @product["inventory_count"] %></li>
</ul>

app/views/stores/index.html.erb
<h1>List of Stores</h1>
<table class="Pure-table-bordered">
  <tr>
    <th>Store Name</th>
    <th>Street Address</th>
    <th>City</th>
  </tr>
<% @stores['result'].each do |store| %>
  <section>
    <tr>
      <td><%= link_to store['name'], store_path(store['id']) %></td>
      <td><%= store['address_line_1'] %></td>
      <td><%= store['city'] %></td>
    </tr>
  </section>
<% end %>

app/views/stores/show.html.erb
<h1><%= @store['name'] %></h1>
<table class="pure-table pure-table-bordered">
  <tr>
    <td>
      <%= @store['address_line_1'] %><br>
      <%= @store['address_line_2'] %><br>
      <%= @store['city'] %>, Ontario 
      <%= @store['postal_code'] %>
    </td>
  </tr>
   
</table>

<table>
  <tr>
    <th>Sun</th>
    <th>Mon</th>
    <th>Tu-F</th>
    <th>Sat</th>
  </tr>
  <tr>
    <th><%= @store['sunday_open'] / 60 %> - <%= (@store['sunday_close'] / 60) - 12 %>pm</th>
    <th><%= @store['monday_open'] / 60 %> - <%= (@store['monday_close'] / 60) - 12 %>pm</th>
    <th><%= @store['tuesday_open'] / 60 %> - <%= (@store['tuesday_close'] / 60) - 12 %>pm</th>
    <th><%= @store['saturday_open'] / 60 %> - <%= (@store['saturday_close'] / 60) - 12 %>pm</th>
  </tr>
</table>